import Container from './components/Container'
import Navbar from './components/navbar/NavbarComp'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} id='body' >
        <Container>
          <Navbar />
          <div className='pb-20 pt-28'>
            </div>
          {children}
        </Container>
      </body>
    </html>
  )
}
